_partial_: True
_target_: disentangle.models.QuantizedAE
encoder_partial: ???
latent_partial:
  _partial_: True
  _target_: disentangle.latents.LFQuantizedLatent
  num_latents: ???
  should_bound: False

decoder_partial: ???
lambdas:
  binary_cross_entropy: 1.
  quantization: 0.
  commitment: 0.01
  entropy: 0.0001
  l2: 0.0001  # adamw
  l1: 0.