_partial_: True
_target_: disentangle.models.QuantizedAE
encoder_partial: ???
latent_partial:
  _partial_: True
  _target_: disentangle.latents.QuantizedLatent
  num_latents: ???
  num_values_per_latent: 10
  optimize_values: True
decoder_partial: ???
lambdas:
  binary_cross_entropy: 1.
  quantization: 1.
  commitment: 0.001
  l2: 0.1  # adamw
  l1: 0.